name: generate-builds
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate-soh-otr:
    runs-on: ${{ (vars.LINUX_RUNNER && fromJSON(vars.LINUX_RUNNER)) || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-soh-otr-ccache
    - name: Install dependencies
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        sudo apt-get update
        sudo apt-get install -y $(cat .github/workflows/apt-deps.txt)
    - name: Install latest SDL
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        wget https://www.libsdl.org/release/SDL2-2.26.1.tar.gz
        tar -xzf SDL2-2.26.1.tar.gz
        cd SDL2-2.26.1
        ./configure
        make -j 10
        sudo make install
        sudo cp -av /usr/local/lib/libSDL* /lib/x86_64-linux-gnu/
    - name: Install latest SDL_net
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        wget https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.2.0.tar.gz
        tar -xzf SDL2_net-2.2.0.tar.gz
        cd SDL2_net-2.2.0
        ./configure
        make -j 10
        sudo make install
        sudo cp -av /usr/local/lib/libSDL* /lib/x86_64-linux-gnu/
    - name: Generate soh.otr
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release
        cmake --build build-cmake --config Release --target GenerateSohOtr
    - uses: actions/upload-artifact@v4
      with:
        name: soh.otr
        path: soh.otr
        retention-days: 1
  build-switch:
    needs: generate-soh-otr
    runs-on: ${{ (vars.LINUX_RUNNER && fromJSON(vars.LINUX_RUNNER)) || 'ubuntu-latest' }}
    container:
      image: devkitpro/devkita64:20251117
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
    - name: Fix dubious ownership error
      if: ${{ vars.LINUX_RUNNER }}
      run: git config --global --add safe.directory '*'
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-switch-ccache
    - name: Build SoH
      run: |
        cmake -H. -Bbuild-switch -GNinja -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
        cmake --build build-switch --target soh_nro -j3

        mv build-switch/soh/*.nro soh.nro
        mv README.md readme.txt
    - name: Download soh.otr
      uses: actions/download-artifact@v4
      with:
        name: soh.otr
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: soh-switch
        path: |
          soh.nro
          soh.otr
          readme.txt
